// Generated by generate.py

package io.grpc.monitoring.streamz;

import com.google.common.base.Preconditions;
import com.google.common.collect.ImmutableList;

import java.util.Set;

import javax.annotation.Generated;

/**
 * A four-dimensional Counter. This is essentially a
 * Metric4<F1, F2, F3, F4, Long>,
 * with restricted API that only permits incrementing the metric.
 *
 * <p>This class may only be instantiated through a {@link MetricFactory}.
 *
 * @param <F1> The type of the first metric field.
 * @param <F2> The type of the second metric field.
 * @param <F3> The type of the third metric field.
 * @param <F4> The type of the fourth metric field.
 * @author konigsberg@google.com (Robert Konigsberg)
 */
@Generated(value = "generate.py")
public class Counter4<F1, F2, F3, F4>
    extends StoredMetric<Long, Counter4<F1, F2, F3, F4>> {

  Counter4(String name, ValueTypeTraits<Long> traits, Metadata metadata,
      ImmutableList<? extends Field<?>> fields) {
    super(name, traits, metadata, fields);
    Preconditions.checkArgument(getNumFields() == 4);
  }

  /**
   * @see StoredCell#increment()
   */
  public void increment(
      Metric4.CellKey<F1, F2, F3, F4> key) {
    super.increment(key);
  }

  /**
   * @see #increment(Metric4.CellKey<F1, F2, F3, F4>)
   */
  public void increment(
      F1 field1,
      F2 field2,
      F3 field3,
      F4 field4) {
    increment(Metric4.createCellKey(
        field1, field2, field3, field4));
  }

  /**
   * @see StoredCell#incrementBy(Number)
   */
  public void incrementBy(
      Metric4.CellKey<F1, F2, F3, F4> key,
      long value) {
    super.incrementBy(key, value);
  }

  /**
   * @see #increment(Metric4.CellKey<F1, F2, F3, F4>, long)
   */
  public void incrementBy(
      F1 field1,
      F2 field2,
      F3 field3,
      F4 field4,
      long value) {
    incrementBy(
        Metric4.createCellKey(
            field1, field2, field3, field4),
        value);
  }

  /**
   * @see StoredMetric#clear(FieldTuple)
   */
  public void clear(
      Metric4.CellKey<F1, F2, F3, F4> key) {
    super.clear(key);
  }

  /**
   * @see #clear(Metric4.CellKey<F1, F2, F3, F4>)
   */
  public void clear(
      F1 field1,
      F2 field2,
      F3 field3,
      F4 field4) {
    clear(Metric4.createCellKey(
        field1, field2, field3, field4));
  }

  /**
   * @see StoredCell#getValue()
   */
  public Long get(
      Metric4.CellKey<F1, F2, F3, F4> key) {
    return super.get(key);
  }

  /**
   * @see #get(Metric4.CellKey<F1, F2, F3, F4>)
   */
  public Long get(
      F1 field1,
      F2 field2,
      F3 field3,
      F4 field4) {
    return get(Metric4.createCellKey(
        field1, field2, field3, field4));
  }

  /**
   * @see StoredMetric#keySet()
   */
  // We ensure that only FieldTuples created by createCellKey are used as keys in the map
  @SuppressWarnings("unchecked")
  @Override
  public Set<Metric4.CellKey<F1, F2, F3, F4>> keySet() {
    return (Set<Metric4.CellKey<F1, F2, F3, F4>>) super.keySet();
  }
}