// Generated by generate.py

package io.grpc.monitoring.streamz;

import com.google.common.base.Preconditions;
import com.google.common.collect.ImmutableList;

import java.util.Set;

import javax.annotation.Generated;

/**
 * A five-dimensional Counter. This is essentially a
 * Metric5<F1, F2, F3, F4, F5, Long>,
 * with restricted API that only permits incrementing the metric.
 *
 * <p>This class may only be instantiated through a {@link MetricFactory}.
 *
 * @param <F1> The type of the first metric field.
 * @param <F2> The type of the second metric field.
 * @param <F3> The type of the third metric field.
 * @param <F4> The type of the fourth metric field.
 * @param <F5> The type of the fifth metric field.
 * @author konigsberg@google.com (Robert Konigsberg)
 */
@Generated(value = "generate.py")
public class Counter5<F1, F2, F3, F4, F5>
    extends StoredMetric<Long, Counter5<F1, F2, F3, F4, F5>> {

  Counter5(String name, ValueTypeTraits<Long> traits, Metadata metadata,
      ImmutableList<? extends Field<?>> fields) {
    super(name, traits, metadata, fields);
    Preconditions.checkArgument(getNumFields() == 5);
  }

  /**
   * @see StoredCell#increment()
   */
  public void increment(
      Metric5.CellKey<F1, F2, F3, F4, F5> key) {
    super.increment(key);
  }

  /**
   * @see #increment(Metric5.CellKey<F1, F2, F3, F4, F5>)
   */
  public void increment(
      F1 field1,
      F2 field2,
      F3 field3,
      F4 field4,
      F5 field5) {
    increment(Metric5.createCellKey(
        field1, field2, field3, field4, field5));
  }

  /**
   * @see StoredCell#incrementBy(Number)
   */
  public void incrementBy(
      Metric5.CellKey<F1, F2, F3, F4, F5> key,
      long value) {
    super.incrementBy(key, value);
  }

  /**
   * @see #increment(Metric5.CellKey<F1, F2, F3, F4, F5>, long)
   */
  public void incrementBy(
      F1 field1,
      F2 field2,
      F3 field3,
      F4 field4,
      F5 field5,
      long value) {
    incrementBy(
        Metric5.createCellKey(
            field1, field2, field3, field4, field5),
        value);
  }

  /**
   * @see StoredMetric#clear(FieldTuple)
   */
  public void clear(
      Metric5.CellKey<F1, F2, F3, F4, F5> key) {
    super.clear(key);
  }

  /**
   * @see #clear(Metric5.CellKey<F1, F2, F3, F4, F5>)
   */
  public void clear(
      F1 field1,
      F2 field2,
      F3 field3,
      F4 field4,
      F5 field5) {
    clear(Metric5.createCellKey(
        field1, field2, field3, field4, field5));
  }

  /**
   * @see StoredCell#getValue()
   */
  public Long get(
      Metric5.CellKey<F1, F2, F3, F4, F5> key) {
    return super.get(key);
  }

  /**
   * @see #get(Metric5.CellKey<F1, F2, F3, F4, F5>)
   */
  public Long get(
      F1 field1,
      F2 field2,
      F3 field3,
      F4 field4,
      F5 field5) {
    return get(Metric5.createCellKey(
        field1, field2, field3, field4, field5));
  }

  /**
   * @see StoredMetric#keySet()
   */
  // We ensure that only FieldTuples created by createCellKey are used as keys in the map
  @SuppressWarnings("unchecked")
  @Override
  public Set<Metric5.CellKey<F1, F2, F3, F4, F5>> keySet() {
    return (Set<Metric5.CellKey<F1, F2, F3, F4, F5>>) super.keySet();
  }
}