// Generated by generate.py

package io.grpc.monitoring.streamz;

import com.google.common.base.Preconditions;
import com.google.common.collect.ImmutableList;

import java.util.Set;

import javax.annotation.Generated;

/**
 * A six-dimensional Counter. This is essentially a
 * Metric6<F1, F2, F3, F4, F5, F6, Long>,
 * with restricted API that only permits incrementing the metric.
 *
 * <p>This class may only be instantiated through a {@link MetricFactory}.
 *
 * @param <F1> The type of the first metric field.
 * @param <F2> The type of the second metric field.
 * @param <F3> The type of the third metric field.
 * @param <F4> The type of the fourth metric field.
 * @param <F5> The type of the fifth metric field.
 * @param <F6> The type of the sixth metric field.
 * @author konigsberg@google.com (Robert Konigsberg)
 */
@Generated(value = "generate.py")
public class Counter6<F1, F2, F3, F4, F5, F6>
    extends StoredMetric<Long, Counter6<F1, F2, F3, F4, F5, F6>> {

  Counter6(String name, ValueTypeTraits<Long> traits, Metadata metadata,
      ImmutableList<? extends Field<?>> fields) {
    super(name, traits, metadata, fields);
    Preconditions.checkArgument(getNumFields() == 6);
  }

  /**
   * @see StoredCell#increment()
   */
  public void increment(
      Metric6.CellKey<F1, F2, F3, F4, F5, F6> key) {
    super.increment(key);
  }

  /**
   * @see #increment(Metric6.CellKey<F1, F2, F3, F4, F5, F6>)
   */
  public void increment(
      F1 field1,
      F2 field2,
      F3 field3,
      F4 field4,
      F5 field5,
      F6 field6) {
    increment(Metric6.createCellKey(
        field1, field2, field3, field4, field5, field6));
  }

  /**
   * @see StoredCell#incrementBy(Number)
   */
  public void incrementBy(
      Metric6.CellKey<F1, F2, F3, F4, F5, F6> key,
      long value) {
    super.incrementBy(key, value);
  }

  /**
   * @see #increment(Metric6.CellKey<F1, F2, F3, F4, F5, F6>, long)
   */
  public void incrementBy(
      F1 field1,
      F2 field2,
      F3 field3,
      F4 field4,
      F5 field5,
      F6 field6,
      long value) {
    incrementBy(
        Metric6.createCellKey(
            field1, field2, field3, field4, field5, field6),
        value);
  }

  /**
   * @see StoredMetric#clear(FieldTuple)
   */
  public void clear(
      Metric6.CellKey<F1, F2, F3, F4, F5, F6> key) {
    super.clear(key);
  }

  /**
   * @see #clear(Metric6.CellKey<F1, F2, F3, F4, F5, F6>)
   */
  public void clear(
      F1 field1,
      F2 field2,
      F3 field3,
      F4 field4,
      F5 field5,
      F6 field6) {
    clear(Metric6.createCellKey(
        field1, field2, field3, field4, field5, field6));
  }

  /**
   * @see StoredCell#getValue()
   */
  public Long get(
      Metric6.CellKey<F1, F2, F3, F4, F5, F6> key) {
    return super.get(key);
  }

  /**
   * @see #get(Metric6.CellKey<F1, F2, F3, F4, F5, F6>)
   */
  public Long get(
      F1 field1,
      F2 field2,
      F3 field3,
      F4 field4,
      F5 field5,
      F6 field6) {
    return get(Metric6.createCellKey(
        field1, field2, field3, field4, field5, field6));
  }

  /**
   * @see StoredMetric#keySet()
   */
  // We ensure that only FieldTuples created by createCellKey are used as keys in the map
  @SuppressWarnings("unchecked")
  @Override
  public Set<Metric6.CellKey<F1, F2, F3, F4, F5, F6>> keySet() {
    return (Set<Metric6.CellKey<F1, F2, F3, F4, F5, F6>>) super.keySet();
  }
}