// Generated by generate.py

package io.grpc.monitoring.streamz;

import com.google.common.base.Preconditions;
import com.google.common.collect.ImmutableList;

import java.util.Set;

import javax.annotation.Generated;

/**
 * A seven-dimensional Counter. This is essentially a
 * Metric7<F1, F2, F3, F4, F5, F6, F7, Long>,
 * with restricted API that only permits incrementing the metric.
 *
 * <p>This class may only be instantiated through a {@link MetricFactory}.
 *
 * @param <F1> The type of the first metric field.
 * @param <F2> The type of the second metric field.
 * @param <F3> The type of the third metric field.
 * @param <F4> The type of the fourth metric field.
 * @param <F5> The type of the fifth metric field.
 * @param <F6> The type of the sixth metric field.
 * @param <F7> The type of the seventh metric field.
 * @author konigsberg@google.com (Robert Konigsberg)
 */
@Generated(value = "generate.py")
public class Counter7<F1, F2, F3, F4, F5, F6, F7>
    extends StoredMetric<Long, Counter7<F1, F2, F3, F4, F5, F6, F7>> {

  Counter7(String name, ValueTypeTraits<Long> traits, Metadata metadata,
      ImmutableList<? extends Field<?>> fields) {
    super(name, traits, metadata, fields);
    Preconditions.checkArgument(getNumFields() == 7);
  }

  /**
   * @see StoredCell#increment()
   */
  public void increment(
      Metric7.CellKey<F1, F2, F3, F4, F5, F6, F7> key) {
    super.increment(key);
  }

  /**
   * @see #increment(Metric7.CellKey<F1, F2, F3, F4, F5, F6, F7>)
   */
  public void increment(
      F1 field1,
      F2 field2,
      F3 field3,
      F4 field4,
      F5 field5,
      F6 field6,
      F7 field7) {
    increment(Metric7.createCellKey(
        field1, field2, field3, field4, field5, field6, field7));
  }

  /**
   * @see StoredCell#incrementBy(Number)
   */
  public void incrementBy(
      Metric7.CellKey<F1, F2, F3, F4, F5, F6, F7> key,
      long value) {
    super.incrementBy(key, value);
  }

  /**
   * @see #increment(Metric7.CellKey<F1, F2, F3, F4, F5, F6, F7>, long)
   */
  public void incrementBy(
      F1 field1,
      F2 field2,
      F3 field3,
      F4 field4,
      F5 field5,
      F6 field6,
      F7 field7,
      long value) {
    incrementBy(
        Metric7.createCellKey(
            field1, field2, field3, field4, field5, field6, field7),
        value);
  }

  /**
   * @see StoredMetric#clear(FieldTuple)
   */
  public void clear(
      Metric7.CellKey<F1, F2, F3, F4, F5, F6, F7> key) {
    super.clear(key);
  }

  /**
   * @see #clear(Metric7.CellKey<F1, F2, F3, F4, F5, F6, F7>)
   */
  public void clear(
      F1 field1,
      F2 field2,
      F3 field3,
      F4 field4,
      F5 field5,
      F6 field6,
      F7 field7) {
    clear(Metric7.createCellKey(
        field1, field2, field3, field4, field5, field6, field7));
  }

  /**
   * @see StoredCell#getValue()
   */
  public Long get(
      Metric7.CellKey<F1, F2, F3, F4, F5, F6, F7> key) {
    return super.get(key);
  }

  /**
   * @see #get(Metric7.CellKey<F1, F2, F3, F4, F5, F6, F7>)
   */
  public Long get(
      F1 field1,
      F2 field2,
      F3 field3,
      F4 field4,
      F5 field5,
      F6 field6,
      F7 field7) {
    return get(Metric7.createCellKey(
        field1, field2, field3, field4, field5, field6, field7));
  }

  /**
   * @see StoredMetric#keySet()
   */
  // We ensure that only FieldTuples created by createCellKey are used as keys in the map
  @SuppressWarnings("unchecked")
  @Override
  public Set<Metric7.CellKey<F1, F2, F3, F4, F5, F6, F7>> keySet() {
    return (Set<Metric7.CellKey<F1, F2, F3, F4, F5, F6, F7>>) super.keySet();
  }
}