// Generated by generate.py

package io.grpc.monitoring.streamz;

import com.google.common.base.Preconditions;
import com.google.common.collect.ImmutableList;

import java.util.Set;

import javax.annotation.Generated;

/**
 * A two-dimensional Counter. This is essentially a
 * Metric2<F1, F2, Long>,
 * with restricted API that only permits incrementing the metric.
 *
 * <p>This class may only be instantiated through a {@link MetricFactory}.
 *
 * @param <F1> The type of the first metric field.
 * @param <F2> The type of the second metric field.
 * @author konigsberg@google.com (Robert Konigsberg)
 */
@Generated(value = "generate.py")
public class Counter2<F1, F2>
    extends StoredMetric<Long, Counter2<F1, F2>> {

  Counter2(String name, ValueTypeTraits<Long> traits, Metadata metadata,
      ImmutableList<? extends Field<?>> fields) {
    super(name, traits, metadata, fields);
    Preconditions.checkArgument(getNumFields() == 2);
  }

  /**
   * @see StoredCell#increment()
   */
  public void increment(
      Metric2.CellKey<F1, F2> key) {
    super.increment(key);
  }

  /**
   * @see #increment(Metric2.CellKey<F1, F2>)
   */
  public void increment(
      F1 field1,
      F2 field2) {
    increment(Metric2.createCellKey(
        field1, field2));
  }

  /**
   * @see StoredCell#incrementBy(Number)
   */
  public void incrementBy(
      Metric2.CellKey<F1, F2> key,
      long value) {
    super.incrementBy(key, value);
  }

  /**
   * @see #increment(Metric2.CellKey<F1, F2>, long)
   */
  public void incrementBy(
      F1 field1,
      F2 field2,
      long value) {
    incrementBy(
        Metric2.createCellKey(
            field1, field2),
        value);
  }

  /**
   * @see StoredMetric#clear(FieldTuple)
   */
  public void clear(
      Metric2.CellKey<F1, F2> key) {
    super.clear(key);
  }

  /**
   * @see #clear(Metric2.CellKey<F1, F2>)
   */
  public void clear(
      F1 field1,
      F2 field2) {
    clear(Metric2.createCellKey(
        field1, field2));
  }

  /**
   * @see StoredCell#getValue()
   */
  public Long get(
      Metric2.CellKey<F1, F2> key) {
    return super.get(key);
  }

  /**
   * @see #get(Metric2.CellKey<F1, F2>)
   */
  public Long get(
      F1 field1,
      F2 field2) {
    return get(Metric2.createCellKey(
        field1, field2));
  }

  /**
   * @see StoredMetric#keySet()
   */
  // We ensure that only FieldTuples created by createCellKey are used as keys in the map
  @SuppressWarnings("unchecked")
  @Override
  public Set<Metric2.CellKey<F1, F2>> keySet() {
    return (Set<Metric2.CellKey<F1, F2>>) super.keySet();
  }
}