// Generated by generate.py

package io.grpc.monitoring.streamz;

import com.google.common.base.Preconditions;
import com.google.common.collect.ImmutableList;

import java.util.Set;

import javax.annotation.Generated;

/**
 * A three-dimensional Counter. This is essentially a
 * Metric3<F1, F2, F3, Long>,
 * with restricted API that only permits incrementing the metric.
 *
 * <p>This class may only be instantiated through a {@link MetricFactory}.
 *
 * @param <F1> The type of the first metric field.
 * @param <F2> The type of the second metric field.
 * @param <F3> The type of the third metric field.
 * @author konigsberg@google.com (Robert Konigsberg)
 */
@Generated(value = "generate.py")
public class Counter3<F1, F2, F3>
    extends StoredMetric<Long, Counter3<F1, F2, F3>> {

  Counter3(String name, ValueTypeTraits<Long> traits, Metadata metadata,
      ImmutableList<? extends Field<?>> fields) {
    super(name, traits, metadata, fields);
    Preconditions.checkArgument(getNumFields() == 3);
  }

  /**
   * @see StoredCell#increment()
   */
  public void increment(
      Metric3.CellKey<F1, F2, F3> key) {
    super.increment(key);
  }

  /**
   * @see #increment(Metric3.CellKey<F1, F2, F3>)
   */
  public void increment(
      F1 field1,
      F2 field2,
      F3 field3) {
    increment(Metric3.createCellKey(
        field1, field2, field3));
  }

  /**
   * @see StoredCell#incrementBy(Number)
   */
  public void incrementBy(
      Metric3.CellKey<F1, F2, F3> key,
      long value) {
    super.incrementBy(key, value);
  }

  /**
   * @see #increment(Metric3.CellKey<F1, F2, F3>, long)
   */
  public void incrementBy(
      F1 field1,
      F2 field2,
      F3 field3,
      long value) {
    incrementBy(
        Metric3.createCellKey(
            field1, field2, field3),
        value);
  }

  /**
   * @see StoredMetric#clear(FieldTuple)
   */
  public void clear(
      Metric3.CellKey<F1, F2, F3> key) {
    super.clear(key);
  }

  /**
   * @see #clear(Metric3.CellKey<F1, F2, F3>)
   */
  public void clear(
      F1 field1,
      F2 field2,
      F3 field3) {
    clear(Metric3.createCellKey(
        field1, field2, field3));
  }

  /**
   * @see StoredCell#getValue()
   */
  public Long get(
      Metric3.CellKey<F1, F2, F3> key) {
    return super.get(key);
  }

  /**
   * @see #get(Metric3.CellKey<F1, F2, F3>)
   */
  public Long get(
      F1 field1,
      F2 field2,
      F3 field3) {
    return get(Metric3.createCellKey(
        field1, field2, field3));
  }

  /**
   * @see StoredMetric#keySet()
   */
  // We ensure that only FieldTuples created by createCellKey are used as keys in the map
  @SuppressWarnings("unchecked")
  @Override
  public Set<Metric3.CellKey<F1, F2, F3>> keySet() {
    return (Set<Metric3.CellKey<F1, F2, F3>>) super.keySet();
  }
}