// Generated by generate.py

package io.grpc.monitoring.streamz;

import com.google.common.collect.ImmutableList;
import com.google.protobuf.Any;

import javax.annotation.Generated;

/**
 * A three-dimensional EventMetric.
 *
 * <p>This class may only be instantiated through a {@link MetricFactory}.
 *
 * @param <F1> The type of the first metric field.
 * @param <F2> The type of the second metric field.
 * @param <F3> The type of the third metric field.
 * @author ecurran@google.com (Eoin Curran)
 */
@Generated(value = "generate.py")
public class EventMetric3<F1, F2, F3>
    extends EventMetricBase<EventMetric3<F1, F2, F3>> {
  private final Metric3<F1, F2, F3, Distribution> metric;

  EventMetric3(String name, Bucketer bucketer, Metadata metadata,
      Field<F1> field1,
      Field<F2> field2,
      Field<F3> field3) {
    super(bucketer);
    metric = new Metric3<F1, F2, F3, Distribution>(
        name, ValueTypeTraits.getTraits(Distribution.class), metadata.setCumulative(),
        ImmutableList.of(
            field1,
            field2,
            field3));
    metric.setDefaultValue(new Distribution(bucketer));
  }

  /**
   * Records the given value in the distribution.
   */
  public void record(
      Metric3.CellKey<F1, F2, F3> key,
      double value) {
    if (Distribution.isValidSample(value, 1)) {
      metric.changeUnderLock(key, createChanger(value));
    }
  }

  /**
   * @see #record(Metric3.CellKey<F1, F2, F3>, double)
   */
  public void record(
      F1 field1,
      F2 field2,
      F3 field3,
      double value) {
    record(Metric3.createCellKey(
        field1, field2, field3), value);
  }

  /**
   * Records the given value in the distribution with provided
   * com.google.protobuf.Any attachments. All provided attachments must
   * use different type URL.
   */
  public void recordWithExemplar(
      Metric3.CellKey<F1, F2, F3> key,
      double value, Any... attachments) {
    if (Distribution.isValidSample(value, 1)) {
      metric.changeUnderLock(key, createChanger(value, attachments));
    }
  }

  /**
   * Records the given value in the distribution with provided
   * com.google.protobuf.Any attachments. All provided attachments must
   * use different type URL.
   */
  public void recordWithExemplar(
      F1 field1,
      F2 field2,
      F3 field3,
      double value, Any... attachments) {
    recordWithExemplar(Metric3.createCellKey(
        field1, field2, field3),
        value, attachments);
  }

  /**
   * Records the given value in the distribution, "count" times.
   */
  public void recordMultiple(
      Metric3.CellKey<F1, F2, F3> key,
      double value, long count) {
    if (Distribution.isValidSample(value, count)) {
      metric.changeUnderLock(key, createChanger(value, count));
    }
  }

  /**
   * @see #recordMultiple(Metric3.CellKey<F1, F2, F3>, double, long)
   */
  public void recordMultiple(
      F1 field1,
      F2 field2,
      F3 field3,
      double value, long count) {
    recordMultiple(Metric3.createCellKey(
        field1, field2, field3),
        value, count);
  }

  /**
   * Ensures a distribution is defined for the supplied fields. If there is
   * none, one is created with zero elements. If one already exists for the
   * supplied fields, there is no change.
   *
   * @return this object.
   */
  public EventMetric3<F1, F2, F3> forceCreate(
      Metric3.CellKey<F1, F2, F3> key) {
    metric.getOrCreateCell(key);
    return this;
  }

  /**
   * @see #forceCreate(Metric3.CellKey<F1, F2, F3>)
   */
  public EventMetric3<F1, F2, F3> forceCreate(
      F1 field1,
      F2 field2,
      F3 field3) {
    return forceCreate(Metric3.createCellKey(
        field1, field2, field3));
  }

  /**
   * Returns a copy of the distribution for the specified cell.
   */
  public Distribution get(
      Metric3.CellKey<F1, F2, F3> key) {
    return metric.get(key);
  }

  /**
   * @see #get(Metric3.CellKey<F1, F2, F3>)
   */
  public Distribution get(
      F1 field1,
      F2 field2,
      F3 field3) {
    return get(Metric3.createCellKey(
        field1, field2, field3));
  }

  @Override
  protected StoredMetric<Distribution, ?> getUnderlyingMetric() {
    return metric;
  }
}