// Generated by generate.py

package io.grpc.monitoring.streamz;

import com.google.common.collect.ImmutableList;
import com.google.protobuf.Any;

import javax.annotation.Generated;

/**
 * A one-dimensional EventMetric.
 *
 * <p>This class may only be instantiated through a {@link MetricFactory}.
 *
 * @param <F1> The type of the first metric field.
 * @author ecurran@google.com (Eoin Curran)
 */
@Generated(value = "generate.py")
public class EventMetric1<F1>
    extends EventMetricBase<EventMetric1<F1>> {
  private final Metric1<F1, Distribution> metric;

  EventMetric1(String name, Bucketer bucketer, Metadata metadata,
      Field<F1> field1) {
    super(bucketer);
    metric = new Metric1<F1, Distribution>(
        name, ValueTypeTraits.getTraits(Distribution.class), metadata.setCumulative(),
        ImmutableList.of(
            field1));
    metric.setDefaultValue(new Distribution(bucketer));
  }

  /**
   * Records the given value in the distribution.
   */
  public void record(
      Metric1.CellKey<F1> key,
      double value) {
    if (Distribution.isValidSample(value, 1)) {
      metric.changeUnderLock(key, createChanger(value));
    }
  }

  /**
   * @see #record(Metric1.CellKey<F1>, double)
   */
  public void record(
      F1 field1,
      double value) {
    record(Metric1.createCellKey(
        field1), value);
  }

  /**
   * Records the given value in the distribution with provided
   * com.google.protobuf.Any attachments. All provided attachments must
   * use different type URL.
   */
  public void recordWithExemplar(
      Metric1.CellKey<F1> key,
      double value, Any... attachments) {
    if (Distribution.isValidSample(value, 1)) {
      metric.changeUnderLock(key, createChanger(value, attachments));
    }
  }

  /**
   * Records the given value in the distribution with provided
   * com.google.protobuf.Any attachments. All provided attachments must
   * use different type URL.
   */
  public void recordWithExemplar(
      F1 field1,
      double value, Any... attachments) {
    recordWithExemplar(Metric1.createCellKey(
        field1),
        value, attachments);
  }

  /**
   * Records the given value in the distribution, "count" times.
   */
  public void recordMultiple(
      Metric1.CellKey<F1> key,
      double value, long count) {
    if (Distribution.isValidSample(value, count)) {
      metric.changeUnderLock(key, createChanger(value, count));
    }
  }

  /**
   * @see #recordMultiple(Metric1.CellKey<F1>, double, long)
   */
  public void recordMultiple(
      F1 field1,
      double value, long count) {
    recordMultiple(Metric1.createCellKey(
        field1),
        value, count);
  }

  /**
   * Ensures a distribution is defined for the supplied fields. If there is
   * none, one is created with zero elements. If one already exists for the
   * supplied fields, there is no change.
   *
   * @return this object.
   */
  public EventMetric1<F1> forceCreate(
      Metric1.CellKey<F1> key) {
    metric.getOrCreateCell(key);
    return this;
  }

  /**
   * @see #forceCreate(Metric1.CellKey<F1>)
   */
  public EventMetric1<F1> forceCreate(
      F1 field1) {
    return forceCreate(Metric1.createCellKey(
        field1));
  }

  /**
   * Returns a copy of the distribution for the specified cell.
   */
  public Distribution get(
      Metric1.CellKey<F1> key) {
    return metric.get(key);
  }

  /**
   * @see #get(Metric1.CellKey<F1>)
   */
  public Distribution get(
      F1 field1) {
    return get(Metric1.createCellKey(
        field1));
  }

  @Override
  protected StoredMetric<Distribution, ?> getUnderlyingMetric() {
    return metric;
  }
}