// Generated by generate.py

package io.grpc.monitoring.streamz;

import com.google.common.collect.ImmutableList;
import com.google.protobuf.Any;

import javax.annotation.Generated;

/**
 * A six-dimensional EventMetric.
 *
 * <p>This class may only be instantiated through a {@link MetricFactory}.
 *
 * @param <F1> The type of the first metric field.
 * @param <F2> The type of the second metric field.
 * @param <F3> The type of the third metric field.
 * @param <F4> The type of the fourth metric field.
 * @param <F5> The type of the fifth metric field.
 * @param <F6> The type of the sixth metric field.
 * @author ecurran@google.com (Eoin Curran)
 */
@Generated(value = "generate.py")
public class EventMetric6<F1, F2, F3, F4, F5, F6>
    extends EventMetricBase<EventMetric6<F1, F2, F3, F4, F5, F6>> {
  private final Metric6<F1, F2, F3, F4, F5, F6, Distribution> metric;

  EventMetric6(String name, Bucketer bucketer, Metadata metadata,
      Field<F1> field1,
      Field<F2> field2,
      Field<F3> field3,
      Field<F4> field4,
      Field<F5> field5,
      Field<F6> field6) {
    super(bucketer);
    metric = new Metric6<F1, F2, F3, F4, F5, F6, Distribution>(
        name, ValueTypeTraits.getTraits(Distribution.class), metadata.setCumulative(),
        ImmutableList.of(
            field1,
            field2,
            field3,
            field4,
            field5,
            field6));
    metric.setDefaultValue(new Distribution(bucketer));
  }

  /**
   * Records the given value in the distribution.
   */
  public void record(
      Metric6.CellKey<F1, F2, F3, F4, F5, F6> key,
      double value) {
    if (Distribution.isValidSample(value, 1)) {
      metric.changeUnderLock(key, createChanger(value));
    }
  }

  /**
   * @see #record(Metric6.CellKey<F1, F2, F3, F4, F5, F6>, double)
   */
  public void record(
      F1 field1,
      F2 field2,
      F3 field3,
      F4 field4,
      F5 field5,
      F6 field6,
      double value) {
    record(Metric6.createCellKey(
        field1, field2, field3, field4, field5, field6), value);
  }

  /**
   * Records the given value in the distribution with provided
   * com.google.protobuf.Any attachments. All provided attachments must
   * use different type URL.
   */
  public void recordWithExemplar(
      Metric6.CellKey<F1, F2, F3, F4, F5, F6> key,
      double value, Any... attachments) {
    if (Distribution.isValidSample(value, 1)) {
      metric.changeUnderLock(key, createChanger(value, attachments));
    }
  }

  /**
   * Records the given value in the distribution with provided
   * com.google.protobuf.Any attachments. All provided attachments must
   * use different type URL.
   */
  public void recordWithExemplar(
      F1 field1,
      F2 field2,
      F3 field3,
      F4 field4,
      F5 field5,
      F6 field6,
      double value, Any... attachments) {
    recordWithExemplar(Metric6.createCellKey(
        field1, field2, field3, field4, field5, field6),
        value, attachments);
  }

  /**
   * Records the given value in the distribution, "count" times.
   */
  public void recordMultiple(
      Metric6.CellKey<F1, F2, F3, F4, F5, F6> key,
      double value, long count) {
    if (Distribution.isValidSample(value, count)) {
      metric.changeUnderLock(key, createChanger(value, count));
    }
  }

  /**
   * @see #recordMultiple(Metric6.CellKey<F1, F2, F3, F4, F5, F6>, double, long)
   */
  public void recordMultiple(
      F1 field1,
      F2 field2,
      F3 field3,
      F4 field4,
      F5 field5,
      F6 field6,
      double value, long count) {
    recordMultiple(Metric6.createCellKey(
        field1, field2, field3, field4, field5, field6),
        value, count);
  }

  /**
   * Ensures a distribution is defined for the supplied fields. If there is
   * none, one is created with zero elements. If one already exists for the
   * supplied fields, there is no change.
   *
   * @return this object.
   */
  public EventMetric6<F1, F2, F3, F4, F5, F6> forceCreate(
      Metric6.CellKey<F1, F2, F3, F4, F5, F6> key) {
    metric.getOrCreateCell(key);
    return this;
  }

  /**
   * @see #forceCreate(Metric6.CellKey<F1, F2, F3, F4, F5, F6>)
   */
  public EventMetric6<F1, F2, F3, F4, F5, F6> forceCreate(
      F1 field1,
      F2 field2,
      F3 field3,
      F4 field4,
      F5 field5,
      F6 field6) {
    return forceCreate(Metric6.createCellKey(
        field1, field2, field3, field4, field5, field6));
  }

  /**
   * Returns a copy of the distribution for the specified cell.
   */
  public Distribution get(
      Metric6.CellKey<F1, F2, F3, F4, F5, F6> key) {
    return metric.get(key);
  }

  /**
   * @see #get(Metric6.CellKey<F1, F2, F3, F4, F5, F6>)
   */
  public Distribution get(
      F1 field1,
      F2 field2,
      F3 field3,
      F4 field4,
      F5 field5,
      F6 field6) {
    return get(Metric6.createCellKey(
        field1, field2, field3, field4, field5, field6));
  }

  @Override
  protected StoredMetric<Distribution, ?> getUnderlyingMetric() {
    return metric;
  }
}