// Generated by generate.py

package io.grpc.monitoring.streamz;

import com.google.common.collect.ImmutableList;
import com.google.protobuf.Any;

import javax.annotation.Generated;

/**
 * A nine-dimensional EventMetric.
 *
 * <p>This class may only be instantiated through a {@link MetricFactory}.
 *
 * @param <F1> The type of the first metric field.
 * @param <F2> The type of the second metric field.
 * @param <F3> The type of the third metric field.
 * @param <F4> The type of the fourth metric field.
 * @param <F5> The type of the fifth metric field.
 * @param <F6> The type of the sixth metric field.
 * @param <F7> The type of the seventh metric field.
 * @param <F8> The type of the eighth metric field.
 * @param <F9> The type of the ninth metric field.
 * @author ecurran@google.com (Eoin Curran)
 */
@Generated(value = "generate.py")
public class EventMetric9<F1, F2, F3, F4, F5, F6, F7, F8, F9>
    extends EventMetricBase<EventMetric9<F1, F2, F3, F4, F5, F6, F7, F8, F9>> {
  private final Metric9<F1, F2, F3, F4, F5, F6, F7, F8, F9, Distribution> metric;

  EventMetric9(String name, Bucketer bucketer, Metadata metadata,
      Field<F1> field1,
      Field<F2> field2,
      Field<F3> field3,
      Field<F4> field4,
      Field<F5> field5,
      Field<F6> field6,
      Field<F7> field7,
      Field<F8> field8,
      Field<F9> field9) {
    super(bucketer);
    metric = new Metric9<F1, F2, F3, F4, F5, F6, F7, F8, F9, Distribution>(
        name, ValueTypeTraits.getTraits(Distribution.class), metadata.setCumulative(),
        ImmutableList.of(
            field1,
            field2,
            field3,
            field4,
            field5,
            field6,
            field7,
            field8,
            field9));
    metric.setDefaultValue(new Distribution(bucketer));
  }

  /**
   * Records the given value in the distribution.
   */
  public void record(
      Metric9.CellKey<F1, F2, F3, F4, F5, F6, F7, F8, F9> key,
      double value) {
    if (Distribution.isValidSample(value, 1)) {
      metric.changeUnderLock(key, createChanger(value));
    }
  }

  /**
   * @see #record(Metric9.CellKey<F1, F2, F3, F4, F5, F6, F7, F8, F9>, double)
   */
  public void record(
      F1 field1,
      F2 field2,
      F3 field3,
      F4 field4,
      F5 field5,
      F6 field6,
      F7 field7,
      F8 field8,
      F9 field9,
      double value) {
    record(Metric9.createCellKey(
        field1, field2, field3, field4, field5, field6, field7, field8, field9), value);
  }

  /**
   * Records the given value in the distribution with provided
   * com.google.protobuf.Any attachments. All provided attachments must
   * use different type URL.
   */
  public void recordWithExemplar(
      Metric9.CellKey<F1, F2, F3, F4, F5, F6, F7, F8, F9> key,
      double value, Any... attachments) {
    if (Distribution.isValidSample(value, 1)) {
      metric.changeUnderLock(key, createChanger(value, attachments));
    }
  }

  /**
   * Records the given value in the distribution with provided
   * com.google.protobuf.Any attachments. All provided attachments must
   * use different type URL.
   */
  public void recordWithExemplar(
      F1 field1,
      F2 field2,
      F3 field3,
      F4 field4,
      F5 field5,
      F6 field6,
      F7 field7,
      F8 field8,
      F9 field9,
      double value, Any... attachments) {
    recordWithExemplar(Metric9.createCellKey(
        field1, field2, field3, field4, field5, field6, field7, field8, field9),
        value, attachments);
  }

  /**
   * Records the given value in the distribution, "count" times.
   */
  public void recordMultiple(
      Metric9.CellKey<F1, F2, F3, F4, F5, F6, F7, F8, F9> key,
      double value, long count) {
    if (Distribution.isValidSample(value, count)) {
      metric.changeUnderLock(key, createChanger(value, count));
    }
  }

  /**
   * @see #recordMultiple(Metric9.CellKey<F1, F2, F3, F4, F5, F6, F7, F8, F9>, double, long)
   */
  public void recordMultiple(
      F1 field1,
      F2 field2,
      F3 field3,
      F4 field4,
      F5 field5,
      F6 field6,
      F7 field7,
      F8 field8,
      F9 field9,
      double value, long count) {
    recordMultiple(Metric9.createCellKey(
        field1, field2, field3, field4, field5, field6, field7, field8, field9),
        value, count);
  }

  /**
   * Ensures a distribution is defined for the supplied fields. If there is
   * none, one is created with zero elements. If one already exists for the
   * supplied fields, there is no change.
   *
   * @return this object.
   */
  public EventMetric9<F1, F2, F3, F4, F5, F6, F7, F8, F9> forceCreate(
      Metric9.CellKey<F1, F2, F3, F4, F5, F6, F7, F8, F9> key) {
    metric.getOrCreateCell(key);
    return this;
  }

  /**
   * @see #forceCreate(Metric9.CellKey<F1, F2, F3, F4, F5, F6, F7, F8, F9>)
   */
  public EventMetric9<F1, F2, F3, F4, F5, F6, F7, F8, F9> forceCreate(
      F1 field1,
      F2 field2,
      F3 field3,
      F4 field4,
      F5 field5,
      F6 field6,
      F7 field7,
      F8 field8,
      F9 field9) {
    return forceCreate(Metric9.createCellKey(
        field1, field2, field3, field4, field5, field6, field7, field8, field9));
  }

  /**
   * Returns a copy of the distribution for the specified cell.
   */
  public Distribution get(
      Metric9.CellKey<F1, F2, F3, F4, F5, F6, F7, F8, F9> key) {
    return metric.get(key);
  }

  /**
   * @see #get(Metric9.CellKey<F1, F2, F3, F4, F5, F6, F7, F8, F9>)
   */
  public Distribution get(
      F1 field1,
      F2 field2,
      F3 field3,
      F4 field4,
      F5 field5,
      F6 field6,
      F7 field7,
      F8 field8,
      F9 field9) {
    return get(Metric9.createCellKey(
        field1, field2, field3, field4, field5, field6, field7, field8, field9));
  }

  @Override
  protected StoredMetric<Distribution, ?> getUnderlyingMetric() {
    return metric;
  }
}