// Generated by generate.py

package io.grpc.monitoring.streamz.utils;

import io.grpc.monitoring.streamz.Field;

import javax.annotation.Generated;

/**
 * Reference to an four-dimensional Metric. Used for testing.
 *
 * <p>See {@link StreamzTester} for factory methods.
 *
 * @param <F1> The type of the first metric field.
 * @param <F2> The type of the second metric field.
 * @param <F3> The type of the third metric field.
 * @param <F4> The type of the fourth metric field.
 * @param <V> The type of the values stored in metric cells.
 * @author ecurran@google.com (Eoin Curran)
 * @author avrukin@google.com (Adopted / Moved to gRPC & Open Source)
*/
@Generated(value = "generate.py")
public class MetricReferenceTester4<F1, F2, F3, F4, V>
     extends MetricReferenceTester<V> {

  MetricReferenceTester4(StreamzTester tester, String metricName,
      Class<V> valueType,
      Field<F1> field1,
      Field<F2> field2,
      Field<F3> field3,
      Field<F4> field4) {
    super(tester, metricName, valueType, field1,
            field2,
            field3,
            field4);
  }

  MetricReferenceTester4(StreamzTester tester, String metricName, Class<V> valueType,
      String... fieldNames) {
    super(tester, metricName, valueType, fieldNames);
  }
}